### ISSUE TITLE
清除所有配置后无法新添加配置

### ISSUE THREAD

**Issue by gameskyer** [InWILL/Locale_Remulator#10]
因为无法启动枫之谷，索性删了配置重新配，结果发现按钮都点不动了
![image](https://user-images.githubusercontent.com/40234223/155360249-14ad1412-41cc-404d-b1c7-04e7ea2e9a99.png)

**Comment by InWILL** [comment]
删除LRConfig.xml，再运行LREditor就会重新生成配置文件。
