### ISSUE TITLE
使用LR打开vs2022/vs2019，使用vs调试功能，设置的工作目录没有生效

### ISSUE THREAD

**Issue by shan165310175** [InWILL/Locale_Remulator#12]
我的项目是台湾繁体项目，默认编码BIG5，使用LR可以正常查看中文繁体字体，否则是乱码。

VS对解决方案的项目右键 - 属性 - 配置属性下的 - 调试 - 工作目录（设置调试exe的工作目录）
（这里主要是修改调试时候，执行文件的执行目录，你懂的）

通过调试打印，发现读取的还是默认的exe执行目录（release目录），而非自己设置的工作目录。

而使用locale emulator，没有任何问题。

**Comment by InWILL** [comment]
自己测试发现设置的工作目录有效，可否提供更详细的信息。

**Comment by shan165310175** [comment]
不知能否知道你的联系方式或者邮箱，给你演示一下？或者我干脆将工程clone下来，你能直接调试看到效果更好。

**Comment by InWILL** [comment]
Github有公开我的邮箱，InWILL.Phantom@gmail.com

**Comment by shan165310175** [comment]
稍等我马上处理。

**Comment by shan165310175** [comment]
很尴尬的地方。
用LocaleEmulator, VS的VAX插件会有bug造成VS闪退。
用你的LR，VAX插件正常使用，但是调试目录异常，哈。

**Comment by InWILL** [comment]
好的，我会尽力修正调试目录的bug。录制视频的话，请从用LR启动vs开始录制。

**Comment by shan165310175** [comment]
比较奇怪，我拷贝了一份我的工程想精简代码后打包给你，但是文件太多，后面精简到只有main函数，运行调试，这调试路径又正常的。
目前路径不正常情况，只在我现有工程。
然而我debug和release目录都设置了调试的工作目录。也重新清理重建了，依然如此。

**Comment by shan165310175** [comment]
猜测可能是项目路径中有中文。后面试一下如果换成英文路径看看是否还有这类问题。
也不清楚是否是VS2022的问题，现在有2个问题：
1. 上面所述的调试目录问题
2. VS2022搜索文本，遍历搜索的文件不全
