### ISSUE TITLE
请问支持win11 吗 win11 启动没有反应

### ISSUE THREAD

**Issue by lwshowl** [InWILL/Locale_Remulator#16]

**Comment by lwshowl** [comment]
冒险岛启动了，可以看见进程，但是没有CPU 占用，然后闪退无提示

**Comment by InWILL** [comment]
开发环境就是win11，不如检查一下机场。

**Comment by lwshowl** [comment]
好像是登录器把play 跳过了，确实可能是网络问题……

**Comment by lwshowl** [comment]
请问clash win tun 不能进游戏是什么原因哦，开雷神可以进，用的VMESS 代理，支持UDP

**Comment by InWILL** [comment]
clash是能进游戏的，估计是IP被橘子锁了。
认为对代理的讨论不属于LR的项目范围内，没其他问题就关闭issue了。

**Comment by lwshowl** [comment]
好的，感谢
