### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by zjb625** [InWILL/Locale_Remulator#17]
```
---------------------------
MapleStoryV241.tmp - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

测试为大概如果使用Locale_Remulator启动程序A，但程序A再启动程序B时会报告此错误。同样的在使用Locale_Remulator启动MapleStory.exe时，MapleStory.exe再启动Patcher.exe会导致此错误（错误的标题栏显示为Patcher.exe）。

**Comment by InWILL** [comment]
理论上有做二次启动的代码，不过台服的patcher更新似乎与其它服不同，韩日服测试均没有发现此问题。计划在下个版本修正这一问题。
临时应对方案：不通过LR，直接运行patcher更新游戏。

**Comment by InWILL** [comment]
经测试目前版本的LR可以二次启动完成自动更新，确定是使用LR运行而不是Beanfun登陆器运行的吗？

**Comment by InWILL** [comment]
不过测试发现64位的MapleStory.exe运行32位的Patcher.exe，但是32位的Patcher.exe无法运行64位的MapleStory.exe，这个问题将会在下个版本修正。

**Comment by zjb625** [comment]
> 经测试目前版本的LR可以二次启动完成自动更新，确定是使用LR运行而不是Beanfun登陆器运行的吗？

实际上我是在LR运行的旧版本的，32位的MapleStory在尝试启动Patcher.exe时遇到了这个问题。而且issue里提到的错误提示其实是使用LR运行台服的安装程序时遇到的问题(见错误提示的标题)。因此LR看起来在x86程序上二次启动才存在这个问题。实际测试上，x64的MapleStory启动Patcher确实不存在任何问题。很抱歉我没有说明清楚...

**Comment by InWILL** [comment]
测试发现确实在32位程序上二次启动会发生问题，安装程序的问题也会在下个版本一并修复。
