### ISSUE TITLE
建议LRProc启动后不要等待子进程

### ISSUE THREAD

**Issue by yuko1225** [InWILL/Locale_Remulator#19]
https://github.com/InWILL/Locale_Remulator/blob/f29b1ca89dc2569e8ed1523923de9db968cb3293/LRProc/LRProc.cpp#L55
查看代码发现LRProc是有意等待子进程退出后才退出，不过没有理解为何需要这么做，子进程启动后强制结束LRProc似乎也没有副作用。考虑到LE等其他软件都是启动后退出Proc，这点可否优化呢？

**Comment by InWILL** [comment]
LRProc的作用是维持转区信息的内存映射，令子进程创建的子进程也能被转区，对于不会二次启动的程序，强制结束LRProc并没有影响。仔细观察的话LE也是等待子进程退出后才退出的，甚至LE还做到了等待子进程的子进程退出。

**Comment by yuko1225** [comment]
> LRProc的作用是维持转区信息的内存映射，令子进程创建的子进程也能被转区，对于不会二次启动的程序，强制结束LRProc并没有影响。仔细观察的话LE也是等待子进程退出后才退出的，甚至LE还做到了等待子进程的子进程退出。

等待的作用我明白了。我之前使用的版本子进程hook是有BUG，本来就经常hook不上所以LRProc是否有运行没差别。我用master编译了一份测试，子进程hook没问题了，LRProc是否有运行确实影响子进程是否正常工作。

不过你能再确认一下LE/ntleas的行为吗？我确实看不到他们的先导程序存在驻留的行为。

**Comment by InWILL** [comment]
https://github.com/xupefei/Locale-Emulator/blob/master/LEProc/LoaderWrapper.cs#L203
LE/ntleas确实都有驻留，在子进程运行期间也能在任务管理器观察到LE的LEProc常驻。

**Comment by yuko1225** [comment]
> https://github.com/xupefei/Locale-Emulator/blob/master/LEProc/LoaderWrapper.cs#L203 LE/ntleas确实都有驻留，在子进程运行期间也能在任务管理器观察到LE的LEProc常驻。

LE原本是不依赖于常驻的，这个文件的话，commit历史显示是最新版才加入的常驻特性。我正在使用的版本老了一点所以不会常驻，但是子进程以及子进程的子进程都可以正常hook。LEProc最新版改成常驻的原因可能是为了兼容Win11。

LR现阶段似乎很依赖于LRProc常驻，LRProc一旦退出，子进程的子进程不仅可能无法转区，还可能会直接崩。
用枫之谷举例，自动更新：LRProc->Maplestory->Patcher->Maplestory退出->等待LRProc退出->Patcher更新完成后无法启动游戏（猜测是崩溃了 不弹区域框）
另一个例子：LRProc->cmd.exe->start cmd.exe->退出第一个cmd.exe->等待LRProc退出->start powershell.exe->powershell崩溃

如果LRProc常驻无法绕开，建议加固一下对子进程的子进程的检测，并且document一下这个行为。

**Comment by InWILL** [comment]
是的，我也正在研究LE为啥可以对二次启动的检测。
目前对维护转区信息有几种方案：
1.LRProc进程维护内存映射
2.创建转区信息临时文件
3.子进程创建孙进程时,对子进程暂停5秒,以维护孙进程转区

**Comment by yuko1225** [comment]
> 是的，我也正在研究LE为啥可以对二次启动的检测。 目前对维护转区信息有几种方案： 1.LRProc进程维护内存映射 2.创建转区信息临时文件 3.子进程创建孙进程时,对子进程暂停5秒,以维护孙进程转区

我有个粗糙的想法，LRProc随机生成一串session id，用这个session id创建内存映射名，然后把session id通过环境变量传入子进程。子进程透过这个环境变量打开内存映射以后不要关闭句柄。session id可以确保内存映射唯一性

因为不关闭句柄，Windows会一直保留这段内存映射直到所有的关联进程都退出，这样既解决了孙进程问题，又不需要LRProc保持运行。

**Comment by yuko1225** [comment]
如果要做的更“干净完美”一些的话，可以把session id同时嵌入映射内存中，孙进程启动并读取了配置后，把环境变量还原回去。孙进程创建玄孙进程时，再从配置文件里读出session id然后通过环境变量传下去，以此类推。

这样即使是一些极端情况，应该也不需要担心有问题。

**Comment by InWILL** [comment]
原本也有考虑使用环境变量，但认为简洁的代码应该减少对系统的修改，所以没有采用。

**Comment by yuko1225** [comment]
@InWILL 当然不是全局的环境变量呀，这个变量只对LR启动的子孙进程有效，设置变量传入子进程，子进程DLL启动的时候还原回去，应该对于子进程是无感。其他的进程/系统也都不会看到这个环境变量。

现在的实现肯定是不行，所有的内存映射都用同一个名字，那么如果我要启动一个日语程序一个繁体程序，然后他们还要启动孙进程的话，肯定会有冲突。

**Comment by InWILL** [comment]
问题就是在于DetourCreateProcessWithDllExA是无法传入变量的，所以才采用内存映射这种绕远路的方式。不然LE/ntlea就能支持多程序转区了。

**Comment by yuko1225** [comment]
> 问题就是在于DetourCreateProcessWithDllExA是无法传入变量的，所以才采用内存映射这种绕远路的方式。不然LE/ntlea就能支持多程序转区了。

LE确实支持多程序转区，刚才亲测，不同区域的子进程孙进程不冲突

BOOL DetourCreateProcessWithDllEx(
    _In_opt_    LPCTSTR lpApplicationName,
    _Inout_opt_ LPTSTR lpCommandLine,
    _In_opt_    LPSECURITY_ATTRIBUTES lpProcessAttributes,
    _In_opt_    LPSECURITY_ATTRIBUTES lpThreadAttributes,
    _In_        BOOL bInheritHandles,
    _In_        DWORD dwCreationFlags,
    **_In_opt_    LPVOID lpEnvironment,**
    _In_opt_    LPCTSTR lpCurrentDirectory,
    _In_        LPSTARTUPINFOW lpStartupInfo,
    _Out_       LPPROCESS_INFORMATION lpProcessInformation,
    _In_        LPCSTR lpDllName,
    _In_opt_    PDETOUR_CREATE_PROCESS_ROUTINEW pfCreateProcessW
);
加粗的这个参数可以定义子进程使用的environment block，根据MS文档
https://docs.microsoft.com/en-us/windows/win32/procthread/changing-environment-variables
稍微修改就可以控制子进程使用的环境变量

**Comment by InWILL** [comment]
Windows对内存泄漏有回收机制，传session确实无法被读取。
不过通过环境变量传配置确实是一个很好的想法。

**Comment by InWILL** [comment]
现已正式通过环境变量传递转区信息。

**Comment by login404** [comment]
能添加个驻留选项么?
行为不用改回去
驻留时什么都不用做
单纯等待程序跟随退出就行了

因为我是配合[启动器](https://yap.rolandtoth.hu/)用的
但其不支持等待其他进程

**Comment by InWILL** [comment]
> 能添加个驻留选项么? 行为不用改回去 驻留时什么都不用做 单纯等待程序跟随退出就行了
> 
> 因为我是配合[启动器](https://yap.rolandtoth.hu/)用的 但其不支持等待其他进程

如果没有重大问题，应该不会再考虑驻留后台。如果有需要的话，可以将LRCommonLibrary和LRProc里面的驻留代码取消注释，自行编译一份。
