### ISSUE TITLE
LREditor建立快捷方式时，要运行的程序路径包含空格则无法成功运行程序

### ISSUE THREAD

**Issue by eagle0701** [InWILL/Locale_Remulator#20]
程序是安装在Program Files路径下的，使用LREditor建立快捷方式后，双击建立的快捷方式无法成功运行程序。手动修改创建的快捷方式，为路径包含空格的程序加上双引号也不行。如果程序安装的路径没有空格，就能够使用创建的快捷方式成功运行程序。

系统：Windows 10 Enterprise LTSC 2019 X64

**Comment by InWILL** [comment]
这个问题并不是因为路径包含空格，而是因为Program Files路径下创建文件需要管理员权限，用管理员身份运行LREditor就能创建。这个问题将会在下个版本修复。

**Comment by eagle0701** [comment]
我这边的路径是 `D:\Program Files`，应该是没有权限问题的。
刚才我使用管理员权限运行 LREditor 来创建快捷方式，使用创建好的快捷方式运行程序也不行。
现在的问题是快捷方式能创建出来，但是用这个快捷方式没法运行程序。

**Comment by InWILL** [comment]
快捷方式无法运行，那右键菜单的方式能运行吗？

**Comment by eagle0701** [comment]
可以运行的。同样的程序我把那个程序安装到不包含空格的路径中，然后用 LREditor 创建的快捷方式也可以运行的

**Comment by InWILL** [comment]
确定是1.4.3版本吧，刚才测试包含空格的路径快捷方式能够运行，这就有点奇怪了。可以的话，请将创建的快捷方式的属性截图发一份。

**Comment by eagle0701** [comment]
目标：`"D:\Program Files (x86)\Locale_Remulator.1.4.3\LRProc.exe" a9de9913-e8b5-4567-8528-5107ece907a7 "D:\Program Files (x86)\Locale_Remulator.1.4.3\LRHookx64.dll" D:\Program Files\Gamania\MapleStory\MapleStory.exe`
起始位置：`"D:\Program Files\Gamania\MapleStory"`


![2022-05-24_121121](https://user-images.githubusercontent.com/1721377/169947333-52d7220a-890b-4dad-8db5-407c6558f534.jpg)

谢谢~

**Comment by InWILL** [comment]
已确认问题所在，LR的路径和游戏的路径前缀空格之前部分相同就会发生这个问题，将在下个版本修正这一问题。

**Comment by eagle0701** [comment]
谢谢~

**Comment by InWILL** [comment]
1.4.4-beta.1版已修复
