### ISSUE TITLE
是否可以在LREditor添加<Timezone>配置项

### ISSUE THREAD

**Issue by shoushangdetuolaji** [InWILL/Locale_Remulator#23]
# 是否可以在LREditor添加<Timezone>配置项
- 有个韩服游戏半韩半乱码,感觉不是默认gulim字体问题
- 作者的le支持谷歌/edge太强了，我看了原生版本的LeConfig.xml提供<Timezone>配置项
- 不知道是否这个因素可以决定到游戏一些字体不解码的问题
- 感谢作者可以看看

**Comment by shoushangdetuolaji** [comment]
提的issue不是很好
补充一下：
我看了原生版本的LeConfig.xml
提供配置项 
`区域选择<Timezone>`

**Comment by InWILL** [comment]
Timezone时区 是LE为了应对时区检测而设计的功能，LR也会预定增加。半韩文半乱码我也在想是什么原因导致的，不过推测应该不是Timezone的问题。

**Comment by shoushangdetuolaji** [comment]
> Timezone时区 是LE为了应对时区检测而设计的功能，LR也会预定增加。半韩文半乱码我也在想是什么原因导致的，不过推测应该不是Timezone的问题。

感谢作者解答，期待作者的生产力:D

**Comment by InWILL** [comment]
请问是哪个韩服游戏，最近需要进一步调试。

**Comment by shoushangdetuolaji** [comment]
> 

是 韩服的 talesrunner

**Comment by shoushangdetuolaji** [comment]
该游戏也是网页登录启动游戏程序的，LE版本是修改注册表的参数，后来被游戏里的反外挂程序xigncode3检测到，就行不通了。
然后尝试LRe的就可以通过xigncode3，但该游戏一些字体是乱码的起码不是???的形式，
应该是一些字体无法识别的问题？（我也不确定）
或者一些文字是客户端动态生成的？（涉及到timezone配置项？）
辛苦作者😥

**Comment by InWILL** [comment]
好的 感谢反馈 我会尽力处理

**Comment by InWILL** [comment]
v1.4.6已修复

**Comment by shoushangdetuolaji** [comment]
> v1.4.6已修复

感谢作者，想给作者买杯咖啡☕
但出现了一个小问题，确保电脑本地系统以安装gulim&batang的朝鲜字体包

但是游戏字体过于蚂蚁小了
- 异常状态
![QQ图片20220821214812](https://user-images.githubusercontent.com/37497536/185794277-6b45f793-7714-42b0-a5a5-8576a058957e.png)
![QQ图片20220821214817](https://user-images.githubusercontent.com/37497536/185794282-eaabeae2-39be-4e47-9e5b-c4b4b8cbba6c.png)

- 正常状态
![QQ图片20220821215422](https://user-images.githubusercontent.com/37497536/185794428-8e15fbc9-5a75-49f3-9190-4263e540fab1.jpg)

作者又幸苦看下了
LE的 是需要安装上面的韩服字体包 才能解决字体蚂蚁小的问题
LRE目前字体恢复正常，但是太小了 T.T

**Comment by shoushangdetuolaji** [comment]
补充问题：
- 有字体丢失的情况
![QQ图片20220822161016](https://user-images.githubusercontent.com/37497536/185872412-72e8ab88-89fa-424f-9d59-f321b922870d.png)

**Comment by shoushangdetuolaji** [comment]
补充问题：
- 有字体丢失
![QQ图片20220822161252](https://user-images.githubusercontent.com/37497536/185872652-0dd4875f-fd15-49a8-9102-ecb1a2f5dc99.png)
![QQ图片20220822161016](https://user-images.githubusercontent.com/37497536/185872659-a8671895-9f81-48a1-b273-3a4a619f76b1.png)
![QQ图片20220822161028](https://user-images.githubusercontent.com/37497536/185872664-7963a6e4-42c3-49fc-9a0b-256755a56e59.png)
![QQ图片20220822161036](https://user-images.githubusercontent.com/37497536/185872669-848dd4d3-bd3e-4f16-acbe-649b8b90f2aa.png)

作者发个咖啡🐎来，实在过意不去了

**Comment by InWILL** [comment]
v1.4.7-beta.1版本尝试修复这一问题，因为我的韩语水平有限，无法分辨是否还有字体丢失的问题。

**Comment by shoushangdetuolaji** [comment]
感谢作者加班解决问题
解决字体小的问题

但是还有个小问题 /(ㄒoㄒ)/~~ 😥

问题：
- 字体拥挤  （LE的是添加韩语输入法解决的，以确保电脑添加了）
![QQ图片20220822215738](https://user-images.githubusercontent.com/37497536/185939733-01825718-54be-4d10-ab51-127488e5da7d.png)
![QQ图片20220822215733](https://user-images.githubusercontent.com/37497536/185939809-2c2a804e-ae30-473f-b32f-00f3a42638a3.png) 这张图是正常的（改系统的unicode显示的）
- 字体缺失（我也不知道啥原因）
![QQ图片20220822220207](https://user-images.githubusercontent.com/37497536/185939966-a704a3c0-c2f5-4152-a3ab-e0637ed05167.png)

- 玩家们聊天框/ 就是一些小地方字体还是很小， （大体字体还是正常）
![QQ图片20220822220344](https://user-images.githubusercontent.com/37497536/185940368-3bbc2ca8-579d-4ae0-8ea3-eef0a9c21020.png)

再次感谢作者

**Comment by InWILL** [comment]
好的 感谢反馈，另外히 끄이악字体缺失的原文是什么呢？

**Comment by shoushangdetuolaji** [comment]
> 好的 感谢反馈，另外히 끄이악字体缺失的原文是什么呢？

就是一个玩家的id是  히렆끄아악
------------------
##  正常显示字体 （改系统区域unicode）
![QQ图片20220822215733](https://user-images.githubusercontent.com/37497536/185951102-1835968c-c617-444e-b208-e7dfb6ab8bdc.png)
-----------------
## 使用LRE 后 
一方面是 **字体拥挤**
二方面是 **字体丢失** 这里的图2就丢失了 `렆` (fjv)
![QQ图片20220822215738](https://user-images.githubusercontent.com/37497536/185951251-e2f407dc-5212-4328-9ccf-3a9ed915f59d.png)
![QQ图片20220822220207](https://user-images.githubusercontent.com/37497536/185951264-278a5f30-66dc-42dd-8350-82f45c14ba62.png)


---
----补充
原LE的也会出现字体拥挤情况
通过系统装韩文输入法解决此问题

目前以确保安装了
![QQ图片20220822225247](https://user-images.githubusercontent.com/37497536/185952059-2f2c5a18-3366-4072-9af0-27ba4d12e177.png)

**Comment by shoushangdetuolaji** [comment]
Locale_Remulator.1.4.7-beta.2 修复了字体拥挤和文字丢失，也支持了部分中文字符显示的问题
感谢作者☕

**Comment by InWILL** [comment]
#26 得感谢另一位老哥，我也没想到这两个问题是有关联的

**Comment by tszchun0915** [comment]
你好 關於這款talesrunner的港台服和泰國服好像無法正常運作 請問有辦法讓他正式運作嗎 謝謝
