### ISSUE TITLE
没适配半角片假、半角平假，显示问号。

### ISSUE THREAD

**Issue by gitcpp** [InWILL/Locale_Remulator#24]
LE能正常显示32位的半角，如果后续能解决将非常感谢。但不是刚需。我这里VS2013降级改了改，严格的构造函数一直过不了编译，算了。

**Comment by InWILL** [comment]
可否截图并提供应用程序说明，我会尽力解决。

**Comment by gitcpp** [comment]
举个例子，青鸟使用LE:半角正常
![捕46436346获](https://user-images.githubusercontent.com/69567733/184319251-1c7176fc-f1bc-4464-8ef1-c4338423242d.JPG)
使用LR，半角显示问号
![捕获12121](https://user-images.githubusercontent.com/69567733/184319322-ac307ae7-3971-4856-9411-e3e9546ea96d.JPG)

**Comment by InWILL** [comment]
v1.4.5 对话框显示异常已修复

**Comment by gitcpp** [comment]
非常感谢，局部有效但是问题似乎并没有解决。我把分割好的程序(启动器)传蓝奏。可以做后续研究。
外链:https://wwd.lanzouv.com/b03j90vud 密码:hv1d
![捕获43634634](https://user-images.githubusercontent.com/69567733/185618762-66a237d8-171d-4eb1-bd11-69fd08211aef.JPG)
![捕获25235252](https://user-images.githubusercontent.com/69567733/185618776-1849cf29-d289-48f8-bb32-f93f0c2aad4e.JPG)

**Comment by InWILL** [comment]
v1.4.6已修复

**Comment by gitcpp** [comment]
Well done！问题已彻底解决。
