### ISSUE TITLE
文件路径乱码

### ISSUE THREAD

**Issue by ShangKent** [InWILL/Locale_Remulator#25]
用Locale Remulator加载日语程序时，程序生成的文件或者文件夹只要是带有非ascii字符，无一例外都是乱码。但用Locale Emulator加载的话就没这个问题。

**Comment by InWILL** [comment]
是的，路径带非ascii字符会出现乱码。因为此问题并非必要且优先级较低，（目前仍在思考韩文显示缺失的问题），请允许我暂时决定搁置。

**Comment by InWILL** [comment]
v1.5.0此问题已修正
