### ISSUE TITLE
能否加入系统语言模拟选项

### ISSUE THREAD

**Issue by chenxijun** [InWILL/Locale_Remulator#26]
本人有的时候需要使用一些多语言软件的其他语言显示。在LE是有这个选项的，能否考虑加入这个功能呢？不胜感激。😘

**Comment by InWILL** [comment]
没有太理解问题：“多语言软件的其他语言显示”。可否介绍是哪个软件并截图说明。

**Comment by chenxijun** [comment]
举个例子，我现在在使用英文系统，然后我需要运行中文版Solidworks（因为英文菜菜看不懂），而Solidworks是根据系统语言判断显示语言的，就需要模拟系统语言。

这个功能在LE中是这样的：
<img width="234" alt="image" src="https://user-images.githubusercontent.com/16610294/200180469-4040c493-2f48-46ae-9dd6-a07d8fd7f0b0.png">

除了Solidworks，还有很多程序有这样的特点。例如默认设置下的微软Office。

**Comment by InWILL** [comment]
感谢反馈 理解问题所在了 我会尽力处理

**Comment by InWILL** [comment]
[v1.4.7-beta.2](https://github.com/InWILL/Locale_Remulator/releases/tag/v1.4.7-beta.2)
已增加UI语言模拟功能，但功能尚不完全，此版本供测试使用。

目前效果如下图所示：
![image](https://user-images.githubusercontent.com/13805009/201516559-151edc4f-df5d-4027-80ef-e4660a90148a.png)

可以看到选项框UI内的内容可以变更，但软件的顶部导航栏仍然是英文。

**Comment by chenxijun** [comment]
> [v1.4.7-beta.2](https://github.com/InWILL/Locale_Remulator/releases/tag/v1.4.7-beta.2)
> 已增加UI语言模拟功能，但功能尚不完全，此版本供测试使用。
> 
> 目前效果如下图所示：
> ![image](https://user-images.githubusercontent.com/13805009/201516559-151edc4f-df5d-4027-80ef-e4660a90148a.png)
> 
> 可以看到选项框UI内的内容可以变更，但软件的顶部导航栏仍然是英文。

十分感谢，😘😘😘
