### ISSUE TITLE
发现两个bug

### ISSUE THREAD

**Issue by HIllya51** [InWILL/Locale_Remulator#27]
1、使用命令行调用LRProc.exe时，目标程序目录不能带有空格（无反应）
2、目标程序发生窗口切换后转区失效，变成乱码。

示例程序为 [パープルソフトウェア] 青春フラジャイル
https://i.postimg.cc/NGdkmwBZ/2022-11-17-202822.jpg

**Comment by HIllya51** [comment]
いつまでも息子のママじゃいられない！3
完全无法运行

**Comment by InWILL** [comment]
感谢反馈 我会尽力处理

**Comment by InWILL** [comment]
1. 程序路径可以带空格 但是不能带双引号”“，这是为了 #20 生成快捷方式时，能方便地在命令行后添加参数而做的设定。后续考虑加入滤除双引号的代码以修正这个问题。
`LRProc.exe LRHookx64.dll d60125ad-a4ff-47b8-8330-2f61c03b2265 E:\GalGame\1188693\mama\ma ma\musu_mam3.exe`

2. 青春フラジャイル 实际窗口切换后并没有发现转区失效的现象，可否详细说明。

3.  いつまでも息子のママじゃいられない！3 已确认问题所在，将会在下一个版本修正这一问题。

**Comment by InWILL** [comment]
1. v1.5.0开始，LRProc调用参数发生改变，新参数如下
LRProc.exe d60125ad-a4ff-47b8-8330-2f61c03b2265 "E:\ma ma\musu_mam3.exe"
有无双引号不再产生影响

3. v1.5.0此问题已修正

**Comment by HIllya51** [comment]
emm 使用1.5.0后，[青春フラジャイル]在设置界面正常（之前也是正常的其实）
然后进入游戏界面窗口全黑，标题不加载，1秒左右后闪退。
![屏幕截图 2023-01-26 201224](https://user-images.githubusercontent.com/101191390/214832557-7e07d621-9974-4246-8712-c7219c6de816.jpg)
![屏幕截图 2023-01-26 201235](https://user-images.githubusercontent.com/101191390/214832565-69c60b78-b752-46b3-b8e0-4c0c4e7ca65b.jpg)

**Comment by InWILL** [comment]
实际测试发现问题与#33 相同，程序路径带非ascii字符，导致程序调用mog3x32.dll和mog3x64.dll失败，进而导致程序崩溃。
如果路径为全英文字符则能够正常运行。

**Comment by InWILL** [comment]
[v1.5.1](https://github.com/InWILL/Locale_Remulator/releases/tag/v1.5.1) 此问题已修正
