### ISSUE TITLE
无法添加右键菜单/Cannot register right-click menu

### ISSUE THREAD

**Issue by WuYunzz** [InWILL/Locale_Remulator#3]
运行register.bat，并且重启电脑或者资源管理器，右键exe文件时没看到新增有相关功能，是哪里操作不对吗，以前添加过LE。Run `register.bat`, Right-click EXE file did not see the new related functions。

**Comment by WuYunzz** [comment]
> 运行register.bat，并且重启电脑或者资源管理器，右键exe文件时没看到新增有相关功能，是哪里操作不对吗，以前添加过LE。Run `register.bat`, Right-click EXE file did not see the new related functions。

win10家庭中文版，版本号21H1

**Comment by InWILL** [comment]
已确认在某些情况下，右键菜单会注册失败，计划在下一个版本中使用全新的注册方式 以修正这一问题。

**Comment by WuYunzz** [comment]
> 

感谢！
