### ISSUE TITLE
能否添加txt文本转区运行

### ISSUE THREAD

**Issue by fekcxz** [InWILL/Locale_Remulator#31]
win11 64位系统每次都要转区运行Notepad.exe再拉入txt文本

**Comment by InWILL** [comment]
LR只对exe可执行程序提供支持，txt文本本质也是调用notepad.exe。
实际上可以通过LR创建notepad.exe的转区快捷方式，进而使用此应用打开。
不过比起这样绕弯子使用LR，推荐直接安装notepad++
