### ISSUE TITLE
文件路径和系统语言模拟的一些问题

### ISSUE THREAD

**Issue by ShangKent** [InWILL/Locale_Remulator#33]
1. 用LR运行程序时，如果程序路径带有非ascii字符且程序本身不支持模拟编码以外的编码的话，程序会无法运行，而LE不存在这个问题。
例：在中文环境下，路径名带有正常显示的日语字符，用LR模拟日语环境运行时会出错或者无法运行，而LE可以运行。

2. 路径为全ascii编码且勾选系统语言模拟时，存在部分程序（如wolf RPG制作的游戏）依旧无法运行的问题（LE可运行）。

3. 有些支持多语言的程序在用LR运行时，程序运行环境似乎没有正确对应到模拟的语言（已勾选模拟系统语言）。
例：
![QQ截图20230126144107](https://user-images.githubusercontent.com/62099673/214775842-b8cb61c9-8a3a-4b0d-9d6e-e2854db82dc9.png)
![QQ截图20230126144128](https://user-images.githubusercontent.com/62099673/214775852-ac09136f-f5f9-4bd0-a63d-3692655a9efd.png)
（LE加载，系统语言模拟为日语）

![QQ截图20230126144158](https://user-images.githubusercontent.com/62099673/214775856-6af52c34-6a52-4969-9465-beec11d5c2a6.png)
![QQ截图20230126144212](https://user-images.githubusercontent.com/62099673/214775860-a8d0ec74-c068-46a1-9268-a33a76c4b8c0.png)
（LR加载，系统语言模拟为日语）

**Comment by InWILL** [comment]
感谢反馈
1. 程序本体带非ascii字符是没问题的，但是如果程序调用的dll库路径带非ascii字符，仍然会出错。这点解决方法已经有思路。
2.3. 还需要进一步分析

**Comment by InWILL** [comment]
[v1.5.2](https://github.com/InWILL/Locale_Remulator/releases/latest) 此问题已修正
