### ISSUE TITLE
提一个LE有但是LR至今没有加入的功能

### ISSUE THREAD

**Issue by wekiname** [InWILL/Locale_Remulator#34]
右键某个程序所关联的文件格式，右键菜单会出现LE的选项，此时可以选择用LE打开并直接调用所关联的程序。
可能表述不清楚，举个例子。

txt格式一般是用系统自带的notepad打开的，而notepad至今仍是32位程序(win10，win11不清楚）。所以右键一个txt文件，此时可以选择 Locale Emulator→run in japanese 直接调用notepad打开这个txt文件，并且会模拟日语环境打开。

那么再说一个64位程序，winrar是有64位的，我所安装的正是64位winrar。那么我们这时右键rar文件是不会有LE菜单的，但是LR的菜单也没有。那么想要直接打开一个rar文件就很费劲了。需要先找的winrar的目录，然后右键winrar.exe，再选择用LR打开，在打开的winrar里再找到我要打开的rar文件，这样可以说是非常不方便了。

至于这样有什么意义，txt文件应该很好理解，文本内容乱码了。压缩文件则是里面的文件夹或者文件名乱码了，转区打开才能看到正确的文件名。

**Comment by InWILL** [comment]
理解对非exe文件进行转区的需求了，会对非exe文件提供一个可选功能。
不过最近没时间，会鸽一段时间更新 ~~（在开坑新项目，Maplestory也还在绝赞爆肝迷雾岛~~

**Comment by wekiname** [comment]
> 理解对非exe文件进行转区的需求了，会对非exe文件提供一个可选功能。 不过最近没时间，会鸽一段时间更新 ~（在开坑新项目，Maplestory也还在绝赞爆肝迷雾岛~

谢谢，能更新就行，这个功能我确实很需要

**Comment by InWILL** [comment]
[v1.5.1](https://github.com/InWILL/Locale_Remulator/releases/tag/v1.5.1) 此功能已实装
