### ISSUE TITLE
如何转区网页启动的网络游戏【韩服DNF】

### ISSUE THREAD

**Issue by 1208041822** [InWILL/Locale_Remulator#35]
网页登录账号然后点击开始游戏会启动neoplelauncher更新器 跑完更新验证然后才会自动启动游戏客户端 不知道如何进行转区启动

**Comment by InWILL** [comment]
用LR转区启动chrome，再在chrome网页登录即可

**Comment by 1208041822** [comment]
> 用LR转区启动chrome，再在chrome网页登录即可

太牛了 解决大问题了 咱们有交流群吗？

**Comment by 1208041822** [comment]
> 用LR转区启动chrome，再在chrome网页登录即可

管理员模式转区才有效果 但是1分钟左右游戏必卡死 这种问题有解吗？

**Comment by InWILL** [comment]
v1.5.0 和 v1.4.7-beta.2
请分别尝试后，看看游戏是否还会卡死。

**Comment by 1208041822** [comment]
> v1.5.0 和 v1.4.7-beta.2 请分别尝试后，看看游戏是否还会卡死。
我刚换了v1.4.7_beta2 功能无效 游戏不会卡死

**Comment by 1208041822** [comment]
> > v1.5.0 和 v1.4.7-beta.2 请分别尝试后，看看游戏是否还会卡死。
> > 我刚换了v1.4.7_beta2 功能无效 游戏不会卡死

之前是一直在使用v1.5.0

**Comment by InWILL** [comment]
好的 我大概知道问题在哪了。目前用v1.4.7-beta.2就好。
v1.5.0的bug下个版本将会一并修复。
关于讨论群，并不打算创建，GitHub的issues就足够了。

**Comment by 1208041822** [comment]
> 好的 我大概知道问题在哪了。目前用v1.4.7-beta.2就好。 v1.5.0的bug下个版本将会一并修复。 关于讨论群，并不打算创建，GitHub的issues就足够了。

额..1.4.7-beta2是无效的 不好使

**Comment by InWILL** [comment]
功能无效是指？

**Comment by 1208041822** [comment]
> 功能无效是指？

就是进游戏没效果 打不了韩语

**Comment by 1208041822** [comment]
> > 功能无效是指？
> 
> 就是进游戏没效果 打不了韩语

最新版是有效的可以打韩语 但是1分钟左右必掉线

**Comment by InWILL** [comment]
不对呀，v1.4.7-beta2 与 v1.5.0 应该没有这个区别呀。
请检查一下v1.4.7-beta.2是否真正执行转区。
近期我也会下载游戏实际测试一下。

**Comment by 1208041822** [comment]
> 不对呀，v1.4.7-beta2 与 v1.5.0 应该没有这个区别呀。 请检查一下v1.4.7-beta.2是否真正执行转区。 近期我也会下载游戏实际测试一下。

![2023 03 06 12 52 34](https://user-images.githubusercontent.com/28993260/223022233-9b1da71d-ea6c-4f17-8f3e-f377a97c2e77.png)

**Comment by 1208041822** [comment]
> 不对呀，v1.4.7-beta2 与 v1.5.0 应该没有这个区别呀。 请检查一下v1.4.7-beta.2是否真正执行转区。 近期我也会下载游戏实际测试一下。

稍等我再测试下 好像刚才是我失误

**Comment by 1208041822** [comment]
> 不对呀，v1.4.7-beta2 与 v1.5.0 应该没有这个区别呀。 请检查一下v1.4.7-beta.2是否真正执行转区。 近期我也会下载游戏实际测试一下。

这回测试可以了 刚才1.4.7无效貌似是我没用管理员运行生成快捷方式的问题？ 而且游戏不会掉线了 应该就是一开始你知道的问题所在。

**Comment by InWILL** [comment]
好的 感谢反馈 此问题将在下一版本修正

**Comment by 1208041822** [comment]
> 好的 感谢反馈 此问题将在下一版本修正

啊 又卡死掉线了

**Comment by InWILL** [comment]
看起来更像是代理的问题 不如尝试一下更换线路

**Comment by 1208041822** [comment]
> 看起来更像是代理的问题 不如尝试一下更换线路

这个可以确定不是代理的问题 不转区可以挂机一周都没问题 我刚才又测试了几次 问题依旧

**Comment by InWILL** [comment]
感谢反馈 这几天我会下载游戏实际测试一下 我会尽力处理

**Comment by 1208041822** [comment]
> 感谢反馈 这几天我会下载游戏实际测试一下 我会尽力处理

好的 辛苦您了 如果需要的话我这边随时也可以让您远程测试

**Comment by InWILL** [comment]
韩服游戏似乎都需要手机号注册，可否提供一个空账号用于测试。
InWILL.Phantom@gmail.com
