### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by HIllya51** [InWILL/Locale_Remulator#36]
新作[ルネ] エルフェンキング，启动后会有一个小的弹窗，使用le可以正常看到这个弹窗，但使用LR看不到这个弹窗，会一直黑着。

![屏幕截图 2023-03-31 141009](https://user-images.githubusercontent.com/101191390/229037606-97820aef-7392-4e89-abe8-3099b855d37c.jpg)

**Comment by InWILL** [comment]
感谢反馈，应该是某个窗口函数出bug了

**Comment by InWILL** [comment]
下载游戏实际测试后，发现这一问题只存在于旧版LR，请更新至最新版[v1.5.2](https://github.com/InWILL/Locale_Remulator/releases/latest)

**Comment by HIllya51** [comment]
咦，还真是，抱歉，不好意思，之前下了152install了，但没删151，删了151重新install152就好了，可能不知道为什么没install152成功吧。好的，谢谢。

**Comment by InWILL** [comment]
没事，也谢谢你提供反馈。
