### ISSUE TITLE
体感台服使用好像没有le稳定

### ISSUE THREAD

**Issue by lintx** [InWILL/Locale_Remulator#5]
评测时间不够长（只有几个小时），样本数量也不多（就我一个），但是体感好像很容易提示“侦测到外挂”目前正在不换环境更换le试试

**Comment by lintx** [comment]
使用LE大掉了，现在重启下电脑再试试

**Comment by eslgf** [comment]
LE是啥啊

**Comment by CCasusensa** [comment]
@eslgf  locale emulator

**Comment by mikuyourworld** [comment]
我这里不会 我用lr玩过2 3天吧 都没出问题 2个号

**Comment by lintx** [comment]
应该没有问题了，经过几天测试，和之前差不多，之前可能是电脑本身上有什么问题导致的

**Comment by InWILL** [comment]
感谢测试
