### ISSUE TITLE
彩虹岛韩服 无法正常使用

### ISSUE THREAD

**Issue by Sphiny97** [InWILL/Locale_Remulator#53]
这是它的官网，naver账号
https://latale.game.naver.com/Main/

彩虹岛韩服是通过浏览器启动游戏的，在启动器界面是正常显示韩语，但是进入游戏仍然是中文乱码

**Comment by InWILL** [comment]
此问题已修正[v1.5.4](https://github.com/InWILL/Locale_Remulator/releases/tag/v1.5.4)

**Comment by Sphiny97** [comment]
点击启动游戏，会显示游戏没有安装，没法调出客户端
![QQ图片20240912203255](https://github.com/user-attachments/assets/39a903c7-b27e-4f3f-bff7-f06ab3d4f78d)

**Comment by InWILL** [comment]
此次更新应该是不会影响浏览器启动的，如果旧版本可以浏览器启动，那就说明不是LR的问题。
另外请使用chrome/firefox，edge是无法使用LR的。

**Comment by Sphiny97** [comment]
旧版本和新版本都可以开浏览器，只是启动游戏没反应或提示上面说的没安装游戏
在win10和win7系统里用过Chrome，Edge，搜狗，360，遨游，都没法调出客户端

**Comment by Sphiny97** [comment]
可以提供账号测试。。。如果你需要的话，请告诉我。

**Comment by InWILL** [comment]
等我明天下一个韩服

**Comment by VaultHunterVV** [comment]
> 此次更新应该是不会影响浏览器启动的，如果旧版本可以浏览器启动，那就说明不是LR的问题。 另外请使用chrome/firefox，edge是无法使用LR的。

关于路径的问题，有玩家已经试过了，如果把浏览器和游戏装在一个盘里面就是可以的，但是还是没法转区成功。甚至之前网页打开登录器是可以转成功的，这次更新后这一步都转不成功了。

**Comment by InWILL** [comment]
我也观察到了这个问题，理论上shellexecute内部是会自动调用createprocess的，但彩虹岛shellexecute的启动方式却不会自动调用，目前正在分析这一问题。

**Comment by VaultHunterVV** [comment]
> 我也观察到了这个现象，理论上shellexecute内部是会自动调用createprocess的，但彩虹岛shellexecute的启动方式却不会自动调用，目前正在分析这一问题。

会跟反外挂有关系吗，彩虹岛启动的时候会有个GameGuard.des的进程创建出来。

**Comment by InWILL** [comment]
和gameguard无关，只是winapi的机制，彩虹岛使用的是url启动导致了这一问题。

**Comment by VaultHunterVV** [comment]
> 和gameguard无关，只是winapi的机制，彩虹岛使用的是url启动导致了这一问题。

能修复吗，或者有workaround？

**Comment by InWILL** [comment]
> > 和gameguard无关，只是winapi的机制，彩虹岛使用的是url启动导致了这一问题。
> 
> 能修复吗，或者有workaround？

彩虹岛的启动机制是chrome -> HappyTukLauncher -> LaTaleLauncher -> LaTaleClient
其实到HappyTukLauncher这里都还能转区成功，后面两步shellexecute就不会自动调用CreateProcess了。
试了两天，如果像LE一样处理NtCreateUserProcess底层函数，又要写汇编。。。想想还是算了。
不过我可以提供一个特别版本的LR，只专门用于彩虹岛转区。

**Comment by InWILL** [comment]
[v1.5.4_Latale](https://github.com/InWILL/Locale_Remulator/releases/tag/v1.5.4_Latale)
目前没有什么好的方法解决 32位应用程序使用shellexecute调用64位的问题。
提供Latale特别版本以解决此问题。
