### ISSUE TITLE
LR无法安装

### ISSUE THREAD

**Issue by shan165310175** [InWILL/Locale_Remulator#6]
一开始显示报错，说是没有安装.netcore.app runtime,安装运行时后，依然安装报错
提示：
you must missing frameworks for .NET

**Comment by shan165310175** [comment]
能提供绿色版就最好了。感谢。

**Comment by InWILL** [comment]
要安装.net desktop runtime，估计你装成.net core runtime了。
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer
绿色版正在测试中，预计今天晚点就会发出来。

**Comment by shan165310175** [comment]
是的，结果最后安装了一个遍，最后安装了这个运行时，就能安装成功了。
https://download.visualstudio.microsoft.com/download/pr/72ebbe8e-5175-41da-9046-1890732e0d5a/675ce08d0c1740142305d35692a8685b/windowsdesktop-runtime-6.0.2-win-x86.exe
https://download.visualstudio.microsoft.com/download/pr/efa32b7a-6eec-4d97-9cdc-c7336a29a749/3df4296170397cf60884dae1be3d103b/windowsdesktop-runtime-6.0.2-win-x64.exe

有个BUG：
我使用LREditor.exe编辑运行环境，选择Run in Korean(Admin)之后修改codepage为台湾，font选微软雅黑。
点击另存为，输入名称，保存后，出现崩溃问题。
后来我使用Run in japanese修改后另存为就没有问题了，现在也没重现崩溃问题。

目前用来打开VS2022，台湾繁体项目显示正常了。
感谢，不然LocaleEmulator不支持64位应用搞得真是头疼呀。

**Comment by InWILL** [comment]
这个bug我没能复现，输入的名称是什么。

**Comment by InWILL** [comment]
现在知道是什么问题了。将在下个版本中一起修复。

**Comment by shan165310175** [comment]
Run in taiwan

目前我也没有再复现了。

还有一个建议：
刚启动LREditor时候，是空白的（列表框没有显示已经有的列表），我觉得如果空白时候直接修改选择想要的编码页并且点保存或者另存为，则走新增逻辑会合适一些。
现在新增，只能在原来基础上改，改完后点击另存为。

**Comment by InWILL** [comment]
空白是为了防止配置文件读取失败导致崩溃，在原来基础上修改这一点想保持和LE一致，所以并不打算改变新增逻辑。
