### ISSUE TITLE
启动参数的问题

### ISSUE THREAD

**Issue by kydryy** [InWILL/Locale_Remulator#7]
之前使用le的时候，我是使用LE生成了maplestory.exe的快捷方式，然后自己写了个python脚本，使用快捷方式+参数1+参数2+...+参数N的方式启动游戏，然后把脚本打包成exe，替代掉网页启动的maplestory.exe。但是替换成LR的快捷方式以后似乎就无法正常使用了，想知道如果用LRProc.exe启动程序，是否支持LRProc.exe  your_app.exe args1 args2 args2 这种方式？

**Comment by InWILL** [comment]
目前不支持，计划在下个版本中支持这种方式。

**Comment by kydryy** [comment]
好的，感谢
