### ISSUE TITLE
韩服冒险岛使用LR的两个问题

### ISSUE THREAD

**Issue by Belongtlei** [InWILL/Locale_Remulator#8]
作者你好！在使用LR玩KMS时遇到了两个问题，不知道是否能解决。
1.使用LR打开登陆器，登陆器页面全部显示“？”，可能是转区的问题，之前的LE是没有这个问题的。虽然不影响游戏，但可能与问题2有关；
2.使用LR玩KMS时，虽然文字显示没有问题，但是输入法打字时，时不时会出现一个“？”或者输入法会联想出一个我并没有如入的文字。这导致KMS输入验证码困难。
这是我在使用过程中遇到的状况，希望作者大大能够解决
感谢你做出LR

**Comment by InWILL** [comment]
运行环境是win10吗？
输入法的问题暂时还没有想到好的解决方法，还在商讨。主要我win11不会出现这个问题，一直没复现这个bug。

**Comment by Belongtlei** [comment]
运行环境是WIN11，群里有很多人是WIN10。都出现了差不多得问题，就是输入无法正常使用。
