### ISSUE TITLE
Win7系统还是有乱码问题

### ISSUE THREAD

**Issue by icekylinH** [InWILL/Locale_Remulator#9]
修改Hook Input Method 后 Win10输入是正常的 win7下还是乱码。输入的是測試，出来的是代？。辛苦咨询是否有解决方案。因为虚拟机环境只能是win7

**Comment by icekylinH** [comment]
好的谢谢，还有个问题想请教下，就是Win10系统下打字输入是正常的。但比如说我从游戏外复制一个名字之类的，复制到游戏里就是乱码，这个有没有什么好办法呀，辛苦您了！

**Comment by InWILL** [comment]
复制粘贴还没想到什么好的解法。我身边没有win7没法测试，win7不勾Hook input editor会乱码吗？

**Comment by kydryy** [comment]
win7似乎不勾Hook就不会乱码

**Comment by icekylinH** [comment]
> 复制粘贴还没想到什么好的解法。我身边没有win7没法测试，win7不勾Hook input editor会乱码吗？

好像我跟下面那位结果是一样的 不勾hook就不会乱码 跟win10正好是反的，那就只剩下复制粘贴的问题了

**Comment by InWILL** [comment]
复制粘贴已修复
